apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-1hpl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-1hpl
    app.kubernetes.io/part-of: tkwch-fix-0075-0043-app
  name: devfile-sample-1hpl
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-1hpl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-1hpl
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0-19-tenant/tkwch-fix-0075-0043-app/devfile-sample-1hpl@sha256:50b705e99744589f9dc7525b5d27bdc986a91a9339b7f606c9c42db5cade3c40
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
